### PR TITLE
Add Windows-specific note about stdout initialization at compile-time

### PR DESCRIPTION
**Pull request by KorryKatti**
Added a note about Windows behavior when using `const stdout = std.io.getStdOut().writer()` outside functions. On Windows, this expression is evaluated at compile-time, which may cause issues. The solution is to place it inside a function to avoid compile-time evaluation.

### CODE REVIEW

**Comment by pedropark99** [comment]
Uhmm, interesting, do you know if this issue is documented somewhere? Maybe in a GitHub issue? Or, in a specific section of the official Zig docs?

**Comment by KorryKatti** [comment]
### when the stdout is outside the pub fn function:
#### error:
image
#### code:
image


### when stdout is inside the function :
#### output : 
image

#### code:
image

**Comment by KorryKatti** [comment]
it is probably a windows only problem

**Comment by pedropark99** [comment]
Found two issues that document this specific requirement on Windows:

- https://github.com/ziglang/zig/issues/19864
- https://github.com/ziglang/zig/issues/17186

**Review by pedropark99 — APPROVED** [review]

**Pull request merged**
